apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-express-api
spec:
  storageClassName: {{ .Values.api.class }}
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: {{ .Values.api.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node
          operator: In
          values:
          - code
