apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-express-api
spec:
  storageClassName: {{ .Values.mongo.class}}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
