apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api
spec:
  storageClassName: {{ .Values.api.class}}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
