apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  ports:
  - name: api
    port: {{ .Values.api.port}}
    protocol: TCP
    targetPort: {{ .Values.api.port}}
    nodePort : {{ .Values.api.nodePort}}
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}
