apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  ports:
  - name: mongo-port
    port: {{ .Values.mongo.port }}
    protocol: TCP
    targetPort: {{ .Values.mongo.port }}
  selector:
    app: mongo
  type: ClusterIP
status:
  loadBalancer: {}
